# Databricks Apps configuration manifest
# https://docs.databricks.com/en/dev-tools/databricks-apps/app-configuration.html
command:
  - "streamlit"
  - "run"
  - "streamlit_app.py"

env:
  - name: "STREAMLIT_GATHER_USAGE_STATS"
    value: "false"
  - name: "PYTHONUNBUFFERED"
    value: "1"
